{
    "name": "accorderie_canada",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "views/accorderie.xml",
        "views/achat_ponctuel.xml",
        "views/achat_ponctuel_produit.xml",
        "views/arrondissement.xml",
        "views/cartier.xml",
        "views/categorie.xml",
        "views/categorie_sous_categorie.xml",
        "views/commande.xml",
        "views/commande_membre.xml",
        "views/commande_membre_produit.xml",
        "views/commentaire.xml",
        "views/demande_service.xml",
        "views/dmd_adhesion.xml",
        "views/droits_admin.xml",
        "views/echange_service.xml",
        "views/fichier.xml",
        "views/fournisseur.xml",
        "views/fournisseur_produit.xml",
        "views/fournisseur_produit_commande.xml",
        "views/fournisseur_produit_pointservice.xml",
        "views/info_logiciel_bd.xml",
        "views/log_acces.xml",
        "views/membre.xml",
        "views/mensualite.xml",
        "views/occupation.xml",
        "views/offre_service_membre.xml",
        "views/origine.xml",
        "views/pointservice.xml",
        "views/pointservice_fournisseur.xml",
        "views/pret.xml",
        "views/produit.xml",
        "views/provenance.xml",
        "views/region.xml",
        "views/revenu_familial.xml",
        "views/situation_maison.xml",
        "views/sous_categorie.xml",
        "views/taxe.xml",
        "views/titre.xml",
        "views/type_communication.xml",
        "views/type_compte.xml",
        "views/type_fichier.xml",
        "views/type_tel.xml",
        "views/versement.xml",
        "views/ville.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
