{
    "name": "Project Workflow Design",
    "category": "Project",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "application": True,
    "depends": ["mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/project_workflow_design.xml",
        "views/project_workflow_design_faiblesse.xml",
        "views/project_workflow_design_force.xml",
        "views/project_workflow_design_menace.xml",
        "views/project_workflow_design_objectif.xml",
        "views/project_workflow_design_opportunite.xml",
        "views/project_workflow_design_volet.xml",
        "views/project_workflow_design_volet_box.xml",
        "views/project_workflow_design_volet_liaison.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
