# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl)

from . import accorderie_accorderie
from . import accorderie_arrondissement
from . import accorderie_commentaire
from . import accorderie_demande_service
from . import accorderie_dmd_adhesion
from . import accorderie_droits_admin
from . import accorderie_echange_service
from . import accorderie_fichier
from . import accorderie_membre
from . import accorderie_occupation
from . import accorderie_offre_service
from . import accorderie_origine
from . import accorderie_pointservice
from . import accorderie_provenance
from . import accorderie_quartier
from . import accorderie_region
from . import accorderie_revenu_familial
from . import accorderie_situation_maison
from . import accorderie_titre
from . import accorderie_type_communication
from . import accorderie_type_compte
from . import accorderie_type_fichier
from . import accorderie_type_service
from . import accorderie_type_service_categorie
from . import accorderie_type_service_sous_categorie
from . import accorderie_type_tel
from . import accorderie_ville
