# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl)

from . import (
    accorderie_accorderie,
    accorderie_arrondissement,
    accorderie_commentaire,
    accorderie_demande_adhesion,
    accorderie_demande_service,
    accorderie_droits_admin,
    accorderie_echange_service,
    accorderie_fichier,
    accorderie_membre,
    accorderie_membre_favoris,
    accorderie_occupation,
    accorderie_offre_service,
    accorderie_origine,
    accorderie_point_service,
    accorderie_provenance,
    accorderie_quartier,
    accorderie_region,
    accorderie_revenu_familial,
    accorderie_situation_maison,
    accorderie_type_communication,
    accorderie_type_compte,
    accorderie_type_fichier,
    accorderie_type_service,
    accorderie_type_service_categorie,
    accorderie_type_service_sous_categorie,
    accorderie_type_telephone,
    accorderie_ville,
    accorderie_workflow,
    accorderie_workflow_relation,
    accorderie_workflow_state,
    res_partner,
)
