{
    "name": "Accorderie Canada Ddb data",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "application": True,
    "depends": [
        "accorderie_canada_ddb",
    ],
    "data": [
        "data/accorderie_occupation.xml",
        "data/accorderie_origine.xml",
        "data/accorderie_provenance.xml",
        "data/accorderie_region.xml",
        "data/accorderie_ville.xml",
        "data/accorderie_arrondissement.xml",
        "data/accorderie_quartier.xml",
        "data/accorderie_revenu_familial.xml",
        "data/accorderie_situation_maison.xml",
        "data/accorderie_type_communication.xml",
        "data/accorderie_type_fichier.xml",
        "data/accorderie_type_service_categorie.xml",
        "data/accorderie_type_service_sous_categorie.xml",
        "data/accorderie_type_service.xml",
        "data/accorderie_type_telephone.xml",
    ],
    "installable": True,
}
