{
    "name": "Accorderie Canada Ddb",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "application": True,
    "depends": [
        "portal",
        "website",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/accorderie_accorderie.xml",
        "views/accorderie_canada_ddb_templates.xml",
        "views/accorderie_arrondissement.xml",
        "views/accorderie_commentaire.xml",
        "views/accorderie_demande_adhesion.xml",
        "views/accorderie_demande_service.xml",
        "views/accorderie_droits_admin.xml",
        "views/accorderie_echange_service.xml",
        "views/accorderie_fichier.xml",
        "views/accorderie_membre.xml",
        "views/accorderie_occupation.xml",
        "data/accorderie_occupation.xml",
        "views/accorderie_offre_service.xml",
        "views/accorderie_origine.xml",
        "data/accorderie_origine.xml",
        "views/accorderie_point_service.xml",
        "views/accorderie_provenance.xml",
        "data/accorderie_provenance.xml",
        "views/accorderie_quartier.xml",
        "views/accorderie_region.xml",
        "data/accorderie_region.xml",
        "data/accorderie_ville.xml",
        "data/accorderie_arrondissement.xml",
        "data/accorderie_quartier.xml",
        "views/accorderie_revenu_familial.xml",
        "data/accorderie_revenu_familial.xml",
        "views/accorderie_situation_maison.xml",
        "data/accorderie_situation_maison.xml",
        "views/accorderie_type_communication.xml",
        "data/accorderie_type_communication.xml",
        "views/accorderie_type_compte.xml",
        "views/accorderie_type_fichier.xml",
        "data/accorderie_type_fichier.xml",
        "views/accorderie_type_service.xml",
        "views/accorderie_type_service_categorie.xml",
        "data/accorderie_type_service_categorie.xml",
        "data/accorderie_type_service_sous_categorie.xml",
        "data/accorderie_type_service.xml",
        "views/accorderie_type_service_sous_categorie.xml",
        "views/accorderie_type_telephone.xml",
        "data/accorderie_type_telephone.xml",
        "views/accorderie_ville.xml",
        "views/menu.xml",
        "views/snippets.xml",
        "templates/website.xml",
        "views/accorderie_pub_offre_modal.xml",
    ],
    "installable": True,
}
